services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=norastro
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
